/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */

class Problem2
{
    public Problem2()
    {
        int a = 1;
        int b = 1;
        int c = 2;
        int total = 0;
        while(c < 4000000)
        {
            c = a + b;
            
            if(c % 2 == 0)
            {
                total += c;
            }
            a = b;
            b = c;
        }
        System.out.println(total);
    }
}

